#!/bin/bash

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc

# Remove output from Jupyter notebooks
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace linear_regression_in_r.ipynb
